create table IF not exists PET(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    type varchar(50) NOT NULL,
    description varchar(300)
);

create table if not exists USR(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL,
    password varchar(100) NOT NULL,
    email varchar(150) NOT NULL,
    role varchar(50) NOT NULL
);

create table if not exists ADOPT(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id INT NOT NULL,
    user_id INT NOT NULL,
    creation_time timestamp NOT NULL,
    FOREIGN KEY (pet_id) REFERENCES PET,
    FOREIGN KEY (user_id) REFERENCES USR
);
